### ISSUE TITLE
software station

### ISSUE THREAD

**Issue by Leonardo4752** [ghostbsd/software-station#17]
software station, unstable. It closes alone.
software station, very slow in searching for packages.
[cap.mp4.zip](https://github.com/ghostbsd/ghostbsd/files/5362586/cap.mp4.zip)

**Comment by ericbsd** [comment]
1.1 just got released and should be more stable

**Comment by thedaemon** [comment]
I'm still getting crashes sometimes. Does this help?

`(station-tweak:284): Gtk-WARNING **: 17:36:58.991: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Traceback (most recent call last):
  File "/usr/local/bin/station-tweak", line 449, in <module>
    StationTweak()
  File "/usr/local/bin/station-tweak", line 309, in __init__
    img = theme.load_icon(sidePage.icon, 36, 0)
GLib.Error: rsvg-error-quark: Failed to load /usr/local/share/icons/Vivacious-Colors/apps/scalable/preferences-system-windows.svg: XML parse error: error code=201 (3) in (null):10:53: Namespace prefix sodipodi for docname on svg is not defined
 (0)`

**Comment by haenno** [comment]
I can confirm the error.

btw: it does not occur when running x as root.

**Comment by thedaemon** [comment]
> I can confirm the error.
> 
> btw: it does not occur when running x as root.

Have you ran a recent update? Mine is much more stable now.
