### ISSUE TITLE
Empty list of packages

### ISSUE THREAD

**Issue by simonsaman** [ghostbsd/software-station#18]
Hi there, sometimes the software station opens with zero packages, needs to be closed and opened again to work, I don't know exactly how to reproduce the problem but it have happened to me several times.
![Screenshot at 2020-11-21 18-48-48](https://user-images.githubusercontent.com/74832730/99884021-5f46d880-2c01-11eb-8d0f-1803c1c9af04.png)

**Comment by ericbsd** [comment]
Are you connected to the internet?

**Comment by simonsaman** [comment]
I was connected to the internet, or so I thought. Disconnecting reproduces this behavior.
An alert to the user that the package list couldn't be retrieved, giving option to retry could be a solution. 

PD: So far I'm very happy using this OS, I'm studying the code of software-station to see if I could contribute this solution myself. Thanks for all your efforts to keep this OS.

**Comment by ericbsd** [comment]
I will put that as a feature request.

**Comment by simonsaman** [comment]
Another condition that also triggers this behavior is when pkg `rquery %o` returns `pkg: Repository GhostBSD missing. 'pkg update' required` , this happens even when the computer is connected.

**Comment by pastanton** [comment]
I was able to consistently reproduce this while connected to the internet.

Running `sudo pkg update` fixed it after ignoring a version mismatch for p5-Mail-OpenDKIM.

```
> sudo pkg update
Password:
Updating GhostBSD repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01    
Fetching packagesite.txz: 100%    6 MiB   1.3MB/s    00:05    
Processing entries:   0%
Newer FreeBSD version for package p5-Mail-OpenDKIM:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1300504
- running kernel: 1300500
Ignore the mismatch and continue? [y/N]: y
Processing entries: 100%
GhostBSD repository update completed. 30757 packages processed.
All repositories are up to date.
```

**Comment by ericbsd** [comment]
Ah I see now a message should tell the user to upgrade the system.

**Comment by ericbsd** [comment]
I fixed the issue and added a new feature to warn the user that the system needs to be upgraded
![Screenshot at 2021-06-26 20-30-40](https://user-images.githubusercontent.com/4249848/123524991-41b08480-d6a4-11eb-857a-3e4e6aeaa6f5.png)
