### ISSUE TITLE
Updated to GhostBSD 6-21, and now update-station, software-station, firefox missing gtk support.

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/software-station#23]
Line 790, in <module>, Line 756, in __init___,. 
File /=use/local/lib/python3.8/site-packages/hi/overrides/Gtk.py"
line 515 
Gtk  could not be initialized  Use Gtk.init_check() if you want to handle this case.

Will add picture later.

Rebooted GhostBSD and problem repaired.

**Comment by ericbsd** [comment]
Was that system rebooted after it got updated?

**Comment by wb7odyfred** [comment]
Rebooted and problem was repaired.
So a reboot, and GhostBSD was up and running again.   I wonder if you might consider putting in a  GTK_init_check() function??

**Comment by ericbsd** [comment]
Was that system rebooted after it got updated?

**Comment by ericbsd** [comment]
**Did you see that error before rebooting the upgrade?**

**Comment by ericbsd** [comment]
Still waiting for that anwser

**Comment by ericbsd** [comment]
I can't reproduce it.
