### ISSUE TITLE
Software install feedback UI needs some tweaks

### ISSUE THREAD

**Issue by willbprog127** [ghostbsd/software-station#3]
When installing software with Software Station, when you select one or more software packages to install, then click 'Apply', there is no _obvious_ feedback that something is happening.  It wasn't until a few tries that I noticed the status of the install action was shown at the bottom of the window, with a very light font and progress bar.  Maybe if the status at the bottom was momentarily shaded a light green or some other technique to draw the user's attention to the bottom of the screen, this would let them know something is happening.

Another issue that gives the appearance that nothing is happening after clicking the 'Apply' button is that the 'Apply' button stays enabled after clicking.  The user would typically want to see the button become disabled while work is being done so they are confident the task didn't fail silently.  Disabling the 'Apply' button after clicking also prevents the user from clicking it again while work is already being performed.  I clicked the button twice because I thought my click wasn't registered.  I'm uncertain if this caused any issues with the software installation.

Thank you! :smile:

**Comment by willbprog127** [comment]
What is all this? 😄

**Comment by vimanuelt** [comment]
I will create two tickets for this request.
1. Make progress bar more predominate for viewer.
2. Disable user's ability to select "check" button when "Apply" button has been executed. You want the software installation to complete before being allowed to make additional selections.
