### ISSUE TITLE
Sotware station (GhostBSD 19.04) freezes at 'updating data' when installing a package

### ISSUE THREAD

**Issue by chrisvs** [ghostbsd/software-station#5]
When a simple package is installed (ex. qt5-core) software station freezes after downloading and extracting the package at the stage 'updating data'. The process almost completely uses the CPU. After quitting software station, the python process needs to be killed manually.

Attached you will find the output of vmstat when qt5-core is installed via pkg and the same output when qt5-core is installed via software station

[SS_freeze_vm_stat.txt](https://github.com/ghostbsd/software-station/files/3143193/SS_freeze_vm_stat.txt)

**Comment by ericbsd** [comment]
There have been some changes since 19.04 is it still happening on 19.10+

**Comment by ericbsd** [comment]
I have updated made some changes that should fixed that.
