### ISSUE TITLE
Adding window to confirm changes to softwares on the system

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/software-station#9]
When a user uninstall a package software-station should show the list of packages that depends on it 
and to prompt if user wants to proceed. 
This is needed to avoid accidental uninstall of important packages.

**Comment by ericbsd** [comment]
basically related to https://issues.ghostbsd.org/issues/102

**Comment by ericbsd** [comment]
This window is to confirm before running the installation or deletion of packages with Software Station.
